# Generated by Django 3.1.2 on 2021-03-23 19:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.UUIDField(help_text='Id', primary_key=True, serialize=False, verbose_name='id')),
                ('name', models.CharField(help_text='Название', max_length=100, verbose_name='Название')),
                ('content', models.TextField(help_text='Контент', max_length=300, verbose_name='Контент')),
                ('owner', models.ForeignKey(help_text='Владелец поста', on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL, verbose_name='Владелец поста')),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now=True, help_text='Время лайка', verbose_name='Время лайка')),
                ('liked_by', models.ForeignKey(help_text='Пользователь', on_delete=django.db.models.deletion.CASCADE, related_name='likes', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('post', models.ForeignKey(help_text='Пост', on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='task_api.post', verbose_name='Пост')),
            ],
        ),
        migrations.CreateModel(
            name='Dislike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now=True, help_text='Время дизлайка', verbose_name='Время дизлайка')),
                ('disliked_by', models.ForeignKey(help_text='Пользователь', on_delete=django.db.models.deletion.CASCADE, related_name='dislikes', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('post', models.ForeignKey(help_text='Пост', on_delete=django.db.models.deletion.CASCADE, related_name='dislikes', to='task_api.post', verbose_name='Пост')),
            ],
        ),
    ]
